import { TanstackProvider } from "../../components/providers/TanstackProvider";
import { HeaderBanner } from "../../components/Header/Banner";
import "./globals.css";
//console.log(process.env.NEXT_PUBLIC_BACKENDURL);

// export const metadata: Metadata = {
//   title: "CRM",
//   description: "Generated by create next app",
// };
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <head>
        <title>ADrian</title>
      </head>
      <TanstackProvider>
        <body>
          <HeaderBanner />
          {children}
        </body>
      </TanstackProvider>
    </html>
  );
}
