"use client";
//import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Metadata } from "next";
import { envSchema } from "../../entities/ZodSchemas/env";
import { TanstackProvider } from "../../components/providers/TanstackProvider";
import { MaterialProvider, ThemeProvider } from "../../components/Provider";
//envSchema.parse(process.env);
//texto agregado
console.log(process.env.NEXT_PUBLIC_BACKENDURL);
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "CRM",
//   description: "Generated by create next app",
// };
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TanstackProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <MaterialProvider>{children}</MaterialProvider>
        </body>
      </TanstackProvider>
    </html>
  );
}
